// Dominique Houston
// 1307 - VFW CRUD JSON
var json = {
    "title1": {
        "workTitle": ["Title:", "Stages"],
        "workAuthorName": ["Author:", "Britney Spears"],
        "workAuthorPublished": ["Year Published:", "2002"],
        "workAuthorUrl": ["URL:", "http://www.amazon.com/Britney-Spears-Stages-Sheryl-Berk/dp/097245750X"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Book - Other"],
        "notes": ["Notes:", "It's Britney, b*tch!"],
        "readStart": ["Date Started:", "2003-01-01"],
        "readFinish": ["Date Finished:", "2003-02-02"],
        "stars": ["Rating:", "10"]
    },
    "title2": {
        "workTitle": ["Title:", "The Four Agreements"],
        "workAuthorName": ["Author:", "Don Miguel Ruiz"],
        "workAuthorPublished": ["Year Published:", "1997"],
        "workAuthorUrl": ["URL:", "http://www.amazon.com/Four-Agreements-Practical-Personal-Freedom/dp/1878424319/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Book - Paperback"],
        "notes": ["Notes:", "Life changing read."],
        "readStart": ["Date Started:", "2006-02-01"],
        "readFinish": ["Date Finished:", "2006-02-01"],
        "stars": ["Rating:", "10"]
    },
    "title3": {
        "workTitle": ["Title:", "Rich Kid Smart Kid"],
        "workAuthorName": ["Author:", "Robert T. Kiyosaki"],
        "workAuthorPublished": ["Year Published:", "2001"],
        "workAuthorUrl": ["URL:", "http://www.amazon.com/Rich-Dads-Kid-Smart-Financial/dp/0446677485/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Book - Paperback"],
        "notes": ["Notes:", "It's Britney, b*tch!"],
        "readStart": ["Date Started:", "2001-01-01"],
        "readFinish": ["Date Finished:", ""],
        "stars": ["Rating:", "0"]
    },
    "title4": {
        "workTitle": ["Title:", "Stronger"],
        "workAuthorName": ["Author:", "Serah Mechele"],
        "workAuthorPublished": ["Year Published:", "2002"],
        "workAuthorUrl": ["URL:", "http://google.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Book - Hardcover"],
        "notes": ["Notes:", "I have the power to move on."],
        "readStart": ["Date Started:", "2003-01-01"],
        "readFinish": ["Date Finished:", "2003-01-02"],
        "stars": ["Rating:", "5"]
    },
    "title5": {
        "workTitle": ["Title:", "In-No-Sense"],
        "workAuthorName": ["Author:", "Lindsay Lohan"],
        "workAuthorPublished": ["Year Published:", "2013"],
        "workAuthorUrl": ["URL:", "http://www.lindsaylohan.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Digital - Tablet"],
        "notes": ["Notes:", "Life changing read."],
        "readStart": ["Date Started:", "2013-01-01"],
        "readFinish": ["Date Finished:", "2013-01-02"],
        "stars": ["Rating:", "10"]
    },
    "title6": {
        "workTitle": ["Title:", "Unusual You"],
        "workAuthorName": ["Author:", "Robin Retcher"],
        "workAuthorPublished": ["Year Published:", "2000"],
        "workAuthorUrl": ["URL:", "http://barnesandnoble.com/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Digital - Other"],
        "notes": ["Notes:", "Nothing about you is typical, nothing about you is predictable."],
        "readStart": ["Date Started:", "2001-01-01"],
        "readFinish": ["Date Finished:", "2001-02-03"],
        "stars": ["Rating:", "3"]
    },
    "title7": {
        "workTitle": ["Title:", "Criminal"],
        "workAuthorName": ["Author:", "Geg Shulz"],
        "workAuthorPublished": ["Year Published:", "2003"],
        "workAuthorUrl": ["URL:", "http://gregshulz.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Digital - Personal Computer"],
        "notes": ["Notes:", "To be in love with a criminal is to die."],
        "readStart": ["Date Started:", "2003-01-05"],
        "readFinish": ["Date Finished:", "2003-01-27"],
        "stars": ["Rating:", "4"]
    },
    "title8": {
        "workTitle": ["Title:", "Flyy Girl"],
        "workAuthorName": ["Author:", "Omar Tyree"],
        "workAuthorPublished": ["Year Published:", "2001"],
        "workAuthorUrl": ["URL:", "http://www.omartyree.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Book - Hardcover"],
        "notes": ["Notes:", "One of my favorite books."],
        "readStart": ["Date Started:", "2006-01-01"],
        "readFinish": ["Date Finished:", "2006-01-02"],
        "stars": ["Rating:", "10"]
    },
    "title9": {
        "workTitle": ["Title:", "Bossy Lady"],
        "workAuthorName": ["Author:", "Omar Tyree"],
        "workAuthorPublished": ["Year Published:", "2004"],
        "workAuthorUrl": ["URL:", "http://www.omartyree.com/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Book - Paperback"],
        "notes": ["Notes:", "Not as good as Flyy Girl."],
        "readStart": ["Date Started:", "2005-01-01"],
        "readFinish": ["Date Finished:", "2004-04-23"],
        "stars": ["Rating:", "3"]
    },
    "title10": {
        "workTitle": ["Title:", "Shot Callers"],
        "workAuthorName": ["Author:", "Jean P."],
        "workAuthorPublished": ["Year Published:", "2013"],
        "workAuthorUrl": ["URL:", "http://news.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Digital - Other"],
        "notes": ["Notes:", "I am like the ringleader, I call the shots."],
        "readStart": ["Date Started:", "2013-05-01"],
        "readFinish": ["Date Finished:", "2013-05-02"],
        "stars": ["Rating:", "10"]
    },
    "title11": {
        "workTitle": ["Title:", "The Circus Starring Britney Spears Tour Book"],
        "workAuthorName": ["Author:", "Britney Spears"],
        "workAuthorPublished": ["Year Published:", "2010"],
        "workAuthorUrl": ["URL:", "http://www.britneyspears.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Book - Other"],
        "notes": ["Notes:", "All eyes on me, in the center of the ring."],
        "readStart": ["Date Started:", "2010-07-01"],
        "readFinish": ["Date Finished:", "2010-07-02"],
        "stars": ["Rating:", "10"]
    },
    "title12": {
        "workTitle": ["Title:", "What It Takes to Die Young"],
        "workAuthorName": ["Author:", "Kesha Sebert"],
        "workAuthorPublished": ["Year Published:", "2012"],
        "workAuthorUrl": ["URL:", "http://www.keshasparty.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Book - Other"],
        "notes": ["Notes:", "Turn the music up and dance!"],
        "readStart": ["Date Started:", "2012-05-01"],
        "readFinish": ["Date Finished:", "2012-06-02"],
        "stars": ["Rating:", "7"]
    },
    "title13": {
        "workTitle": ["Title:", "Unapologetic"],
        "workAuthorName": ["Author:", "Robyn Fenty"],
        "workAuthorPublished": ["Year Published:", "2012"],
        "workAuthorUrl": ["URL:", "http://www.rihannadaily.com/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Book - Paperback"],
        "notes": ["Notes:", "Shine bright like a diamond."],
        "readStart": ["Date Started:", "2012-07-01"],
        "readFinish": ["Date Finished:", ""],
        "stars": ["Rating:", "0"]
    },
    "title14": {
        "workTitle": ["Title:", "Pink Friday: Roman's Holiday"],
        "workAuthorName": ["Author:", "Onika Maraj"],
        "workAuthorPublished": ["Year Published:", "2013"],
        "workAuthorUrl": ["URL:", "http://www.mypinkfriday.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Digital - Personal Computer"],
        "notes": ["Notes:", "I'm coming for you, and I won't stop."],
        "readStart": ["Date Started:", "2013-05-01"],
        "readFinish": ["Date Finished:", "2013-07-02"],
        "stars": ["Rating:", "0"]
    },
    "title15": {
        "workTitle": ["Title:", "Photographs"],
        "workAuthorName": ["Author:", "will.i.am"],
        "workAuthorPublished": ["Year Published:", "2010"],
        "workAuthorUrl": ["URL:", "http://www.william.com/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Digital - Other"],
        "notes": ["Notes:", "He tried too hard to be different."],
        "readStart": ["Date Started:", "2010-07-23"],
        "readFinish": ["Date Finished:", "2010-07-28"],
        "stars": ["Rating:", "1"]
    },
    "title16": {
        "workTitle": ["Title:", "How To Womanize"],
        "workAuthorName": ["Author:", "Chris Brown"],
        "workAuthorPublished": ["Year Published:", "2013"],
        "workAuthorUrl": ["URL:", "http://www.chrisbrownweb.com/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "No"],
        "platform": ["Read Platform:", "Book - Other"],
        "notes": ["Notes:", "One of the worst articles I've ever read. Chris Brown needs to return to high school."],
        "readStart": ["Date Started:", "2013-07-12"],
        "readFinish": ["Date Finished:", ""],
        "stars": ["Rating:", "0"]
    },
    "title17": {
        "workTitle": ["Title:", "Take It Back"],
        "workAuthorName": ["Author:", "NyLo Chicago"],
        "workAuthorPublished": ["Year Published:", "2013"],
        "workAuthorUrl": ["URL:", "http://www.hatenylo.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Digital - Personal Computer"],
        "notes": ["Notes:", "It's too late to take it slow."],
        "readStart": ["Date Started:", "2013-06-01"],
        "readFinish": ["Date Finished:", "2013-06-02"],
        "stars": ["Rating:", "10"]
    },
    "title18": {
        "workTitle": ["Title:", "Breakfast at Tiffany's"],
        "workAuthorName": ["Author:", "NyLo Chicago"],
        "workAuthorPublished": ["Year Published:", "2013"],
        "workAuthorUrl": ["URL:", "http://www.hatenylo.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Digital - Tablet"],
        "notes": ["Notes:", "And I kind of like the way it feels like having breakfast at Tiffany's."],
        "readStart": ["Date Started:", "2006-01-01"],
        "readFinish": ["Date Finished:", "2006-01-02"],
        "stars": ["Rating:", "10"]
    },
    "title19": {
        "workTitle": ["Title:", "Fool Me Once"],
        "workAuthorName": ["Author:", "NyLo Chicago"],
        "workAuthorPublished": ["Year Published:", "2001"],
        "workAuthorUrl": ["URL:", "http://www.hatenylo.com/"],
        "workCompleted": ["Work Completed:", "No"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Digital - Tablet"],
        "notes": ["Notes:", "I'm not ready to move on. There's a lot of fish in the sea, that's what my friends tell me."],
        "readStart": ["Date Started:", "2001-01-01"],
        "readFinish": ["Date Finished:", ""],
        "stars": ["Rating:", "10"]
    },
    "title20": {
        "workTitle": ["Title:", "Say It Right"],
        "workAuthorName": ["Author:", "Nelly Furtado"],
        "workAuthorPublished": ["Year Published:", "2004"],
        "workAuthorUrl": ["URL:", "http://www.nellyfurtado.com/"],
        "workCompleted": ["Work Completed:", "Yes"],
        "favorite": ["Marked as Favorite:", "Yes"],
        "platform": ["Read Platform:", "Digital - Other"],
        "notes": ["Notes:", "Oh, you don't mean nothing at all to me."],
        "readStart": ["Date Started:", "2004-06-24"],
        "readFinish": ["Date Finished:", "2004-07-02"],
        "stars": ["Rating:", "10"]
    }

};